"""initial_schema

Revision ID: 0596718f021b
Revises: 
Create Date: 2026-03-03 01:16:51.143028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0596718f021b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_budgets',
    sa.Column('client_key', sa.Text(), nullable=False),
    sa.Column('daily_limit_cents', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('spent_today_cents', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('reset_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('client_key')
    )
    op.create_table('drift_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('drift_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inference_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('client_key', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('policy', sa.Text(), nullable=False),
    sa.Column('prompt_hash', sa.Text(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('cost_cents', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('error_flag', sa.Boolean(), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inference_logs_created_at'), 'inference_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_inference_logs_provider'), 'inference_logs', ['provider'], unique=False)
    op.create_table('provider_stats',
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('ema_latency_mu', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('ema_latency_var', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('ema_cost_mu', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('ema_cost_var', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('ema_quality_mu', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('ema_quality_var', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('provider')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_stats')
    op.drop_index(op.f('ix_inference_logs_provider'), table_name='inference_logs')
    op.drop_index(op.f('ix_inference_logs_created_at'), table_name='inference_logs')
    op.drop_table('inference_logs')
    op.drop_table('drift_snapshots')
    op.drop_table('client_budgets')
    # ### end Alembic commands ###
